name: bensmik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  http: ^1.6.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  google_fonts: ^7.0.2
  chat_bubbles: ^1.7.0
  intl: ^0.20.2
  google_nav_bar: ^5.0.7
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/

# ----------------------------------------
# 🎨 إعدادات الأيقونة (App Icon)
# ----------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false             # 👈 بدلناها لـ false باش ما يقلبش على الآيفون
  image_path: "assets/logo.png"
  min_sdk_android: 21

# ----------------------------------------
# 🚀 إعدادات شاشة البدء (Native Splash)
# ----------------------------------------
flutter_native_splash:
  color: "#6A11CB"
  image: "assets/logo.png"
  android_12:
    color: "#6A11CB"
    image: "assets/logo.png"
  # 👇 حيدنا (أو عطلنا) السطورة ديال iOS
  # ios:
  #   color: "#6A11CB"
  #   image: "assets/logo.png"