// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNvhvXwVhV5FhIyGVaJjMcL2SJODMyUK0',
    appId: '1:170903324082:web:c56724f3920241632250ab',
    messagingSenderId: '170903324082',
    projectId: 'benmsik-e4d3d',
    authDomain: 'benmsik-e4d3d.firebaseapp.com',
    storageBucket: 'benmsik-e4d3d.firebasestorage.app',
    measurementId: 'G-7NK9Z1P9YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7k2GPxtHeFxNYDq2_yXyhJKtopPpFMYo',
    appId: '1:170903324082:android:33b915a0c7a629982250ab',
    messagingSenderId: '170903324082',
    projectId: 'benmsik-e4d3d',
    storageBucket: 'benmsik-e4d3d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQIwUpEEAykVZ0mey-0avoXLZxLZMFBo',
    appId: '1:170903324082:ios:2abce4096bb2c5132250ab',
    messagingSenderId: '170903324082',
    projectId: 'benmsik-e4d3d',
    storageBucket: 'benmsik-e4d3d.firebasestorage.app',
    iosBundleId: 'com.example.bensmik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNvhvXwVhV5FhIyGVaJjMcL2SJODMyUK0',
    appId: '1:170903324082:web:5a96e2e9b48cd7372250ab',
    messagingSenderId: '170903324082',
    projectId: 'benmsik-e4d3d',
    authDomain: 'benmsik-e4d3d.firebaseapp.com',
    storageBucket: 'benmsik-e4d3d.firebasestorage.app',
    measurementId: 'G-33B7DM9GZV',
  );

}